[
    {
        "eventType": "DeliveryOrderUpdate",
        "eventTime": "2024-10-09 15:06:14.050",
        "organizationId": "9fa9f86a-5cc5-40d6-bb13-323754a592ba",
        "correlationId": "deeb9085-d4ca-4556-8058-71ac34309a4c",
        "eventInfo": {
            "id": "d9ab4502-6ffc-40be-9856-2fe8fadc3ed9",
            "posId": "7ee8e4f7-4a57-4469-a4f1-ea0365a0881a",
            "externalNumber": None,
            "organizationId": "9fa9f86a-5cc5-40d6-bb13-323754a592ba",
            "timestamp": 1728486374013,
            "creationStatus": "Success",
            "errorInfo": None,
            "order": {
                "parentDeliveryId": None,
                "customer": {
                    "type": "regular",
                    "id": "feb17adc-fb79-4a38-ad2b-f93043dc3b69",
                    "name": "Shukurulloh Komiljonov",
                    "surname": "kmljnvs",
                    "comment": "Test",
                    "gender": "NotSpecified",
                    "inBlacklist": False,
                    "blacklistReason": None,
                    "birthdate": None,
                },
                "phone": "+998908175047",
                "deliveryPoint": None,
                "status": "WaitCooking",
                "cancelInfo": None,
                "courierInfo": None,
                "completeBefore": "2024-10-09 22:21:13.509",
                "whenCreated": "2024-10-09 20:06:13.569",
                "whenConfirmed": "2024-10-09 20:06:13.569",
                "whenPrinted": None,
                "whenCookingCompleted": None,
                "whenSended": None,
                "whenDelivered": None,
                "comment": None,
                "problem": None,
                "operator": None,
                "marketingSource": None,
                "deliveryDuration": 135,
                "indexInCourierRoute": None,
                "cookingStartTime": "2024-10-09 20:06:13.569",
                "isDeleted": False,
                "whenReceivedByApi": "2024-10-09 15:06:12.682",
                "whenReceivedFromFront": "2024-10-09 15:06:13.111",
                "movedFromDeliveryId": None,
                "movedFromTerminalGroupId": None,
                "movedFromOrganizationId": None,
                "externalCourierService": None,
                "movedToDeliveryId": None,
                "movedToTerminalGroupId": None,
                "movedToOrganizationId": None,
                "menuId": None,
                "deliveryZone": None,
                "estimatedTime": None,
                "sum": 240000.0,
                "number": 33976,
                "sourceKey": "Sector Soft",
                "whenBillPrinted": None,
                "whenClosed": None,
                "conception": None,
                "guestsInfo": {"count": 1, "splitBetweenPersons": False},
                "items": [
                    {
                        "type": "Product",
                        "product": {
                            "id": "b47740bf-6437-4937-b6b2-fec1f628eb1d",
                            "name": "Cup Roll с угрем",
                        },
                        "modifiers": [],
                        "price": 120000.0,
                        "cost": 240000.0,
                        "pricePredefined": False,
                        "positionId": "c8847d34-054c-4005-b9b2-571a4e2834be",
                        "taxPercent": None,
                        "resultSum": 240000.0,
                        "status": "Added",
                        "deleted": None,
                        "amount": 2.0,
                        "comment": None,
                        "whenPrinted": None,
                        "size": None,
                        "comboInformation": None,
                    }
                ],
                "combos": [],
                "payments": [
                    {
                        "paymentType": {
                            "id": "eda4d24f-1dad-4c10-8994-f174221617dd",
                            "name": "Click",
                            "kind": "Card",
                        },
                        "sum": 240000.0,
                        "isPreliminary": False,
                        "isExternal": True,
                        "isProcessedExternally": False,
                        "isFiscalizedExternally": False,
                        "isPrepay": False,
                    }
                ],
                "tips": [],
                "discounts": [],
                "orderType": {
                    "id": "5b1508f9-fe5b-d6af-cb8d-043af587d5c2",
                    "name": "Доставка самовывоз",
                    "orderServiceType": "DeliveryByClient",
                },
                "terminalGroupId": "336d8d3a-2762-4d5f-a3d5-a663682e7e1d",
                "processedPaymentsSum": 0.0,
                "loyaltyInfo": {"coupon": None, "appliedManualConditions": None},
                "externalData": None,
            },
        },
    }
]
