services:
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"

    postgres:
        image: postgres:16
        container_name: postgres
        environment:
            POSTGRES_DB: sushi_yummy
            POSTGRES_USER: sushi
            POSTGRES_PASSWORD: v5jKTw3jbD7t
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    django:
        container_name: django
        build:
            context: ./config
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./config:/usr/src/app
            # - ./locales:/usr/src/app/locales
            # - ./tg_bot:/usr/src/app/tg_bot
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - redis
            - postgres

    # telegram-bot:
    #     container_name: telegram_bot
    #     build:
    #         context: ./config
    #     command: python manage.py bot
    #     volumes:
    #         - ./config:/usr/src/app
    #         - ./locales:/usr/src/app/locales
    #         - ./tg_bot:/usr/src/app/tg_bot
    #     env_file:
    #         - .env
    #     depends_on:
    #         - redis
    #         - postgres

    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: redis-commander
        ports:
            - "5000:8081"
        environment:
            - REDIS_HOSTS=local:redis:6379
        depends_on:
            - redis

    tgbotapi:
        image: aiogram/telegram-bot-api:latest
        env_file:
            - .env
        ports:
            - 8081:8081

volumes:
    postgres_data:
