[
    {
        "eventType": "DeliveryOrderUpdate",
        "eventTime": "2024-10-08 15:48:55.868",
        "organizationId": "9fa9f86a-5cc5-40d6-bb13-323754a592ba",
        "correlationId": "19ea51a8-9a33-451f-a1c5-554b5e3ddb2f",
        "eventInfo": {
            "id": "d8bb83e6-425e-448d-9509-8934b9fb4dc2",
            "posId": "32b3f036-cee8-41f9-8eb1-4a129f2e50b2",
            "externalNumber": "111125",
            "organizationId": "9fa9f86a-5cc5-40d6-bb13-323754a592ba",
            "timestamp": 1728402535851,
            "creationStatus": "Success",
            "errorInfo": None,
            "order": {
                "parentDeliveryId": None,
                "customer": {
                    "type": "regular",
                    "id": "feb17adc-fb79-4a38-ad2b-f93043dc3b69",
                    "name": "Shukurulloh Komiljonov",
                    "surname": "kmljnvs",
                    "comment": "Test",
                    "gender": "NotSpecified",
                    "inBlacklist": False,
                    "blacklistReason": None,
                    "birthdate": None,
                },
                "phone": "+998908175047",
                "deliveryPoint": None,
                "status": "WaitCooking",
                "cancelInfo": None,
                "courierInfo": None,
                "completeBefore": "2024-10-08 23:03:52.300",
                "whenCreated": "2024-10-08 20:48:52.384",
                "whenConfirmed": "2024-10-08 20:48:52.384",
                "whenPrinted": None,
                "whenCookingCompleted": None,
                "whenSended": None,
                "whenDelivered": None,
                "comment": None,
                "problem": None,
                "operator": None,
                "marketingSource": None,
                "deliveryDuration": 135,
                "indexInCourierRoute": None,
                "cookingStartTime": "2024-10-08 20:48:52.384",
                "isDeleted": False,
                "whenReceivedByApi": "2024-10-08 15:48:51.377",
                "whenReceivedFromFront": "2024-10-08 15:48:51.862",
                "movedFromDeliveryId": None,
                "movedFromTerminalGroupId": None,
                "movedFromOrganizationId": None,
                "externalCourierService": None,
                "movedToDeliveryId": None,
                "movedToTerminalGroupId": None,
                "movedToOrganizationId": None,
                "menuId": None,
                "deliveryZone": None,
                "estimatedTime": None,
                "sum": 240000.0,
                "number": 33874,
                "sourceKey": None,
                "whenBillPrinted": None,
                "whenClosed": None,
                "conception": None,
                "guestsInfo": {"count": 1, "splitBetweenPersons": False},
                "items": [
                    {
                        "type": "Product",
                        "product": {
                            "id": "b47740bf-6437-4937-b6b2-fec1f628eb1d",
                            "name": "Cup Roll с угрем",
                        },
                        "modifiers": [],
                        "price": 120000.0,
                        "cost": 240000.0,
                        "pricePredefined": False,
                        "positionId": "f2057a87-74b9-40e4-a82a-c86592a44a8c",
                        "taxPercent": None,
                        "resultSum": 240000.0,
                        "status": "Added",
                        "deleted": None,
                        "amount": 2.0,
                        "comment": None,
                        "whenPrinted": None,
                        "size": None,
                        "comboInformation": None,
                    }
                ],
                "combos": [],
                "payments": [],
                "tips": [],
                "discounts": [],
                "orderType": {
                    "id": "5b1508f9-fe5b-d6af-cb8d-043af587d5c2",
                    "name": "Доставка самовывоз",
                    "orderServiceType": "DeliveryByClient",
                },
                "terminalGroupId": "336d8d3a-2762-4d5f-a3d5-a663682e7e1d",
                "processedPaymentsSum": 0.0,
                "loyaltyInfo": {"coupon": None, "appliedManualConditions": None},
                "externalData": None,
            },
        },
    }
]
